### ISSUE TITLE
send data

### ISSUE THREAD

**Issue by NathalieSchmiedt** [xenovacivus/STM32DiscoveryVCP#3]
Hi,
thanks for sharing your code. Sending  data from the hyper terminal to the board works fine in my case. 
Now I'd like to send data from the stm32f4 to the computer (including a labview project) using your code on the board. Can you please help me which function I have to call? You would really help me.
These are my tries which haven't worked so far:

uint8_t test = 255;
VCP_send_str((uint8_t*)test);

uint8_t test = 255;
VCP_put_char(test);

**Comment by xenovacivus** [comment]
Hi, both of those functions will cause the stm32 to transmit data. The VCP_send_str function expects a null terminated string, so passing in a pointer to a uint8 will send the value, followed by whatever else is in memory till a zero is hit. Your best bet for debugging would be to send a known ASCII character (so its not discarded or misinterpreted by the receiving software). Try VCP_put_char('a') somewhere that can be triggered by a button, ot just in a loop in main. That way, you can be sure the device is sending data after your program (labview) has connected and is ready to receive the data.
